name: Build and Deploy

on:
  # Trigger the workflow on push on main branch,
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: 'true'
    - uses: bobobo80/pelican-to-github-pages@v1.1
      env:
        PELICAN_CONTENT_FOLDER: 'content'
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        # GH_PAGES_CNAME: ${{secrets.DOMAIN_CNAME}}
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        branch: gh-pages
        folder: output
